=== HarshitSingh0203/web-/8/student.dtd
<!ELEMENT students (student+)>

<!ELEMENT student (rollno, name, branch, year, college)>

<!ELEMENT rollno (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT branch (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT college (#PCDATA)>

=== HarshitSingh0203/web-/8/student.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE students SYSTEM "student.dtd">

<?xml-stylesheet type="text/css" href="student.css"?>

<students>
    <student>
        <rollno>101</rollno>
        <name>Harshit Singh</name>
        <branch>CSE</branch>
        <year>2</year>
        <college>UCER</college>
    </student>

    <student>
        <rollno>102</rollno>
        <name>Rahul Kumar</name>
        <branch>CSE</branch>
        <year>2</year>
        <college>UCER</college>
    </student>
</students>
